Repository wecode-bootcamp-korea/45-1st-rgb-frontend, pull requests merged in 2023-05, with the labels that each got.

#1 ADD : 공통으로 사용하는 button 생성
  public/index.html
  src/assets/arrow.png
  src/assets/arrow2.png
  src/assets/button-next.png
  src/assets/button-pre.png
  src/assets/close.png
  src/assets/purple.png
  src/components/Button/Button.js
  src/components/Button/Button.scss
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/pages/User/User.js
  src/styles/reset.scss
Labels: 수정 요청

#6 [45기 김수정] Feature/ProductDescription component
  .stylelintrc.js
  public/data/detailInfo.json
  public/index.html
  src/Router.js
  src/assets/Expand-Arrow.png
  src/assets/viewPw.png
  src/components/Button/Button.js
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUp.scss
  src/pages/ProductDetail/ProductDescription.js
  src/pages/ProductDetail/ProductDescription.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/User/User.js
  src/pages/User/User.scss
  src/styles/common.scss
  src/styles/mixin.scss
  src/styles/reset.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#8 [45기 김수정] Feature/login 기능구현
  src/components/Button/Button.scss
  src/components/CheckBox/CheckBox.js
  src/components/CheckBox/CheckBox.scss
  src/components/Login/Login.js
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUp.scss
  src/pages/User/User.js
  src/pages/User/User.scss
  src/styles/mixin.scss
Labels: 멘토 리뷰 요청

#12 [45기 김수정] feature/signUp/회원가입 필수 기능 구현 완료/ 체크박스 구현중/ 모달창 레이아웃 완성/모달창 기능 추가구현 예정
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUp.scss
  src/components/SignUp/SignUpModal.js
  src/components/SignUp/SignUpModal.scss
Labels: 멘토 리뷰 요청

#7 [45기 이경진] Feature/product detail layout
  public/data/detailInfo.json
  public/images/productDetail/arrow2.png
  public/images/productDetail/blue.png
  public/images/productDetail/button-next.png
  public/images/productDetail/button-pre.png
  public/images/productDetail/plusButton.png
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.js
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.scss
  src/pages/ProductDetail/Components/ImageBox/ImageBox.js
  src/pages/ProductDetail/Components/ImageBox/ImageBox.scss
  src/pages/ProductDetail/Components/Images/Images.js
  src/pages/ProductDetail/Components/Images/Images.scss
  src/pages/ProductDetail/Components/Location/Location.js
  src/pages/ProductDetail/Components/Location/Location.scss
  src/pages/ProductDetail/ProductDescription.js
  src/pages/ProductDetail/ProductDescription.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: 수정 요청

#16 [45기 김수정] Feature/nav
  src/Router.js
  src/assets/rgb.png
  src/components/Login/Login.js
  src/components/Nav/Auth.js
  src/components/Nav/Auth.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUp.scss
  src/components/SignUp/SignUpModal.scss
  src/pages/User/User.js
  src/pages/User/User.scss
Labels: 멘토 리뷰 요청

#15 [45기 이수빈] Feature/main function
  .prettierrc
  public/data/productImage.json
  public/data/productInfo.json
  src/Router.js
  src/assets/delete.png
  src/components/Button/Button.js
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/Cart/CartList.js
  src/components/Cart/CartSum.js
  src/components/Login/Login.js
  src/components/SignUp/SignUp.js
  src/pages/Main/CarouselItem.js
  src/pages/Main/CarouselItem.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainArtist.js
  src/pages/Main/MainArtist.scss
  src/pages/Main/MainArtistNext.js
  src/pages/Main/MainArtistNext.scss
  src/pages/Main/MainCarousel.js
  src/pages/Main/MainCarousel.scss
  src/pages/Main/MainCarousel2.js
  src/pages/Main/MainCarousel2.scss
  src/pages/Main/SecondCarousel.js
  src/pages/Main/SecondCarousel.scss
  src/pages/ProductDetail/ProductDescription.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/User/User.js
Labels: 완료

#19 Feature/sign up
  public/data/API_ADDRESS.js
  src/Router.js
  src/components/Login/Login.js
  src/components/Nav/Auth.js
  src/components/Nav/Auth.scss
  src/components/Nav/Nav.js
  src/components/SignUp/SignUp.js
  src/pages/User/User.scss
Labels: 멘토 리뷰 요청

#5 [45기 문유현] Feature/order layout
  public/data/cartData.json
  public/data/placeOrderData.json
  public/data/productList.json
  public/data/userData.json
  public/images/order/Expand Arrow.png
  public/images/order/arrow-small.png
  public/images/order/arrow2.png
  public/images/order/point_logo.png
  src/components/Button/Button.js
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/Order/components/CheckBox/CheckInput.js
  src/pages/Order/components/CheckBox/CheckInput.scss
  src/pages/Order/components/Delivery/Delivery.js
  src/pages/Order/components/Delivery/Delivery.scss
  src/pages/Order/components/OrderHeader/OrderHeader.js
  src/pages/Order/components/OrderHeader/OrderHeader.scss
  src/pages/Order/components/OrderList/OrderList.js
  src/pages/Order/components/OrderList/OrderList.scss
  src/pages/Order/components/OrderList/components/CheckoutProduct.js
  src/pages/Order/components/OrderList/components/CheckoutProduct.scss
  src/pages/Order/components/Payment/Payment.js
  src/pages/Order/components/Payment/Payment.scss
Labels: 완료

#9 [45기 이원준] Feature/footer layout
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/Notice.js
  src/components/Footer/Notice.scss
  src/components/Footer/Paper.js
  src/components/Footer/Paper.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#22 [45기 김수정] Feature/signup 자동로그인 기능 구현
  src/components/Login/Login.js
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUpModal.js
  src/pages/User/User.js
  src/utils/API_ADDRESS.js
Labels: 멘토 리뷰 요청

#23 [45기 김수정] Feature/nav
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#21 [45기 이수빈] Feature/main function
  public/data/productInfo.json
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/Cart/CartList.js
  src/components/Cart/CartSum.js
  src/components/Nav/Nav.js
  src/pages/Main/CarouselItem.js
  src/pages/Main/Main.js
  src/pages/Main/MainArtist.scss
  src/pages/Main/MainCarousel.js
  src/pages/Main/MainCarousel.scss
  src/pages/Main/MainCarousel2.js
  src/pages/Main/MainCarousel2.scss
  src/pages/Main/MainComingUpArtist.js
  src/pages/Main/MainComingUpArtist.scss
  src/pages/Main/SecondCarousel.scss
Labels: 수정 요청

#4 [45기 이경진] Feature/product list layout
  public/data/artlist.json
  public/data/goodslist.json
  public/images/productList/Expand Arrow.png
  public/images/productList/Expand Arrow2.png
  public/images/productList/productlist.png
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.js
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.scss
  src/pages/ProductDetail/Components/ImageBox/ImageBox.js
  src/pages/ProductDetail/Components/ImageBox/ImageBox.scss
  src/pages/ProductDetail/Components/Images/Images.js
  src/pages/ProductDetail/Components/Images/Images.scss
  src/pages/ProductDetail/Components/Location/Location.js
  src/pages/ProductDetail/ProductDescription.js
  src/pages/ProductDetail/ProductDescription.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/Component/ArtWorks/ArtWorks.js
  src/pages/ProductList/Component/ArtWorks/ArtWorks.scss
  src/pages/ProductList/Component/FilterComponent/FilterComponent.js
  src/pages/ProductList/Component/LeftFilter/LeftFilter.js
  src/pages/ProductList/Component/LeftFilter/LeftFilter.scss
  src/pages/ProductList/Component/ListBottom/ListBottom.js
  src/pages/ProductList/Component/ListBottom/ListBottom.scss
  src/pages/ProductList/Component/ListTop/ListTop.js
  src/pages/ProductList/Component/ListTop/ListTop.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#24 [45기 김수정] Fixed : nav 카트랑 로그인 창 안닫히는 오류 수정/ 아티스트 페이지 연결
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Artists/Artists.js
  src/pages/Artists/Artists.scss
Labels: 멘토 리뷰 요청

#25 [45기 김수정] FIXED : 회원가입 실패 오류 수정
  src/components/SignUp/SignUp.js
Labels: 멘토 리뷰 요청

#27 [45기 이원준] Feature/footer component
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#26 [45기 이수빈] Feature/main/cart function 수정 사항
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/Cart/CartList.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainCarousel.js
  src/pages/Main/MainCarousel2.js
  src/pages/Main/MainCarousel2.scss
Labels: 멘토 리뷰 요청

#28 [45기 이경진]Feature/product
  public/images/productList/SquaresFour.png
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.js
  src/pages/ProductDetail/Components/ImageBox/ImageBox.js
  src/pages/ProductDetail/Components/ImageBox/ImageBox.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/Component/FilterComponent/FilterComponent.js
  src/pages/ProductList/Component/LeftFilter/LeftFilter.scss
  src/pages/ProductList/Component/ListBottom/ListBottom.js
  src/pages/ProductList/Component/ListBottom/ListBottom.scss
Labels: 멘토 리뷰 요청

#29 [45기 문유현] Feature/order 동적 라우팅 구현
  src/Router.js
  src/components/Login/Login.js
  src/components/Nav/Nav.js
  src/components/SignUp/SignUp.js
  src/pages/Invoice/Invoice.js
  src/pages/Order/Order.js
  src/pages/Order/components/Delivery/Delivery.js
  src/pages/Order/components/Payment/Payment.js
  src/pages/Order/components/Payment/Payment.scss
  src/utils/API_ADDRESS.js
Labels: 멘토 리뷰 요청

#32 [45기 김수정] NotFound
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/NotFound/NotFound.js
  src/pages/NotFound/NotFound.scss
Labels: 멘토 리뷰 요청

#31 [45기 이수빈] Feature/artist page
  public/data/productInfo.json
  src/components/Cart/CartList.js
  src/pages/Artists/ArtistProfile.js
  src/pages/Artists/ArtistProfile.scss
  src/pages/Artists/Artists.js
  src/pages/Artists/Artists.scss
  src/pages/Main/CarouselItem.js
  src/pages/Main/CarouselItem.scss
  src/pages/Main/MainCarousel.js
  src/pages/Main/MainCarousel.scss
  src/pages/Main/MainCarousel2.js
  src/pages/Main/MainCarousel2.scss
  src/pages/Main/SecondCarousel.js
  src/utils/API_ADDRESS.js
Labels: 멘토 리뷰 요청

#36 [45기 김수정] FIXED : token undefined 오류 해결
  src/components/Login/Login.js
  src/components/SignUp/SignUp.js
Labels: 멘토 리뷰 요청

#30 [45기 김수정] Feature/check box
  src/components/CheckBox/CheckBox.js
  src/components/CheckBox/CheckBox.scss
  src/components/CheckBox/CheckBoxItem.js
  src/components/CheckBox/CheckBoxItem.scss
  src/components/SignUp/SignUp.js
  src/components/SignUp/SignUp.scss
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/Component/ListBottom/ListBottom.js
  src/utils/API_ADDRESS.js
Labels: 멘토 리뷰 요청

#35 [45기 이수빈] Feature/add
  src/Router.js
  src/components/Cart/CartList.js
  src/components/Nav/Nav.js
  src/pages/Artists/ArtistProfile.js
  src/pages/Artists/ArtistProfile.scss
  src/pages/Artists/Artists.scss
  src/pages/Main/MainCarousel.js
  src/pages/Main/MainCarousel2.js
  src/pages/Order/Order.js
  src/pages/Order/components/Delivery/Delivery.js
  src/pages/Order/components/Payment/Payment.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/Component/ListBottom/ListBottom.js
Labels: 멘토 리뷰 요청

#39 [45기 김수정] Feature/invoice 기능 구현 완료
  src/Router.js
  src/components/Cart/CartList.js
  src/components/Login/Login.js
  src/pages/Invoice/Invoice.js
  src/pages/Invoice/Invoice.scss
  src/pages/Invoice/InvoiceOrderData.js
  src/pages/Invoice/InvoiceOrderData.scss
  src/pages/Invoice/InvoiceUserData.js
  src/pages/Invoice/InvoiceUserData.scss
  src/pages/Main/MainCarousel.js
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.js
Labels: 멘토 리뷰 요청

#43 [45기 이경진 ]Feature/product modify sold out 기능 추가
  src/Router.js
  src/components/Scroll.js
  src/pages/Main/MainCarousel.js
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.js
  src/pages/ProductDetail/Components/DetailInformation/DetailInformation.scss
  src/pages/ProductDetail/Components/ImageBox/ImageBox.js
  src/pages/ProductDetail/ProductDescription.js
  src/pages/ProductDetail/ProductDescription.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/Component/ListBottom/ListBottom.js
  src/pages/ProductList/Component/ListTop/ListTop.js
  src/pages/ProductList/Component/ListTop/ListTop.scss
Labels: 멘토 리뷰 요청

#45 [45기 김수정] ADD : Loading page + favicon 추가
  public/favicon.ico
  src/components/Cart/CartList.js
  src/components/Nav/Nav.js
  src/pages/Invoice/Invoice.js
  src/pages/LoadingPage/LoadingPage.js
  src/pages/LoadingPage/LoadingPage.scss
Labels: 멘토 리뷰 요청

#46 [45기 이수빈] Modify: scss
  src/components/Cart/Cart.scss
  src/pages/Artists/ArtistProfile.js
  src/pages/Artists/ArtistProfile.scss
Labels: 멘토 리뷰 요청

#48 [45기 김수정] Modify all
  public/images/loadingPage/loadingPage.png
  src/Router.js
  src/components/Cart/Cart.scss
  src/components/Nav/Nav.js
  src/pages/LoadingPage/LoadingPage.js
  src/pages/LoadingPage/LoadingPage.scss
  src/pages/Order/components/Payment/Payment.js
  src/pages/ProductList/Component/FilterComponent/FilterComponent.js
Labels: 멘토 리뷰 요청
